### ISSUE TITLE
third-party dependencies on pom-first approach with tycho

### ISSUE THREAD

**Issue by devsprint** [devsprint/org.eclipse.mylyn.github#2]
third-party dependencies could be moved to maven only if those will be available in maven repo as osgi bundles.
Current version of tycho 0.10.0, is not able to handle the dependencies. it looks like a bug... in tycho maven plug-in.

**Comment by devsprint** [comment]
workaround is to keep the third-parties jars in lib folder and refer it from manifest file of core plug-in

**Comment by rombert** [comment]
You should be able to pull in those dependencies from orbit. See https://github.com/rombert/ereviewboard/blob/master/pom.xml for details.

**Comment by devsprint** [comment]
thanks for suggestions. my problem is about third party libs like common-login or google-gson... I'm able to gather correct mylyn/eclipse jars from p2 repo.

**Comment by rombert** [comment]
Did you try adding the orbit p2 repo? 
    <repository>
      <id>orbit</id>
      <layout>p2</layout>
      <url>http://download.eclipse.org/tools/orbit/downloads/drops/R20100519200754/repository/</url>
    </repository>

**Comment by devsprint** [comment]
Fixed bug by referring Orbit repository and updated the manifest file https://github.com/devsprint/org.eclipse.mylyn.github/commit/a1eef8314d0f1e4e12ea32f782f6800a2d671180
