### ISSUE TITLE
Invalid Installation update site

### ISSUE THREAD

**Issue by saidimu** [devsprint/org.eclipse.mylyn.github#21]
This link, from the project README, navigates to a Github error page: "Page does not exist".

http://devsprint.github.com/org.eclipse.mylyn.github/site

**Comment by devsprint** [comment]
The link is made to be used from Update Manager inside Eclipse, not to browse it... If you try to use it from eclipse, it is working properly.

**Comment by saidimu** [comment]
Confirmed it is working from within Eclipse. I'm used to Update sites that are also browseable.

Great plugin btw!
