### ISSUE TITLE
Display labels in task editor

### ISSUE THREAD

**Issue by rombert** [devsprint/org.eclipse.mylyn.github#4]
It would be quite useful to display the labels in the task editor.

**Comment by devsprint** [comment]
I'm thinking of what will be the proper way to display the labels. My initial idea was to try to used as a category in mylyn, but let's see what we will the more useful and intuitive way. I will try both approaches...

**Comment by rombert** [comment]
You can only have one category, so multiple labels will probably not fit. I know bugzilla has a 'keywords' editor which looks good for this purpose.

**Comment by rombert** [comment]
I noticed that labels started showing up, which is really nice.

Only one minor comment - I get one label displayed for tasks which have multiple labels, e.g.  http://github.com/rombert/ereviewboard/issues/issue/31

**Comment by devsprint** [comment]
still trying to figure out how to make the labels editor....

**Comment by rombert** [comment]
Perhaps mapping the attribute to TaskAttribute.KEYWORDS will help? If not, there is a (internal) org.eclipse.mylyn.internal.tasks.ui.editors.CheckboxMultiSelectAttributeEditor class which you can use. This is what the bugzilla connector does.

**Comment by devsprint** [comment]
Yes, I have looked over it, but still thinking if I should use it or not, being marked internal. After I have read the Integrator reference seems that will be ok to use it, but with some risk assumed on my side. However after I will finish the implementation of the functionality   in github connector, I will log a bug in Eclipse bugzilla, letting Mylyn guys know that it may be a candidate for commons.ui API.

**Comment by devsprint** [comment]
Seems that the read only version is working. However I did not had a chance to complete implementation today. I have started to implement People editor part and Comments editor part.

**Comment by rombert** [comment]
I think the updated label editor is quite nice. I've tested it with my own tasks and found only one issue: when multiple labels are selected, only one is 'checked' in the dropdown.

And it probably should be 'Labels' rather than 'Label'.

![Label editor](http://i.imgur.com/N29hB.png)

**Comment by devsprint** [comment]
thanks letting me know. I'm working to push a new release by end of Sunday (March 20th, 2011).

**Comment by devsprint** [comment]
The build published on Sunday, March 20th, 2011, include fixes for problems that you have mention in comment 7.

**Comment by devsprint** [comment]
Fix for problem mention in comment 7.
https://github.com/devsprint/org.eclipse.mylyn.github/commit/8668bc3ee91f1b13957f18c3b1243c320239b910
